import { GeistSans } from "geist/font";
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";
import Error from "@/app/components/Error";
import Navbar from "@/app/components/Navbar";
import AuthProvider from "@/app/components/AuthProvider";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full h-full bg-background">
      <body
        className={
          GeistSans.className + " w-full h-full flex-col bg-background"
        }
      >
        <ErrorBoundary fallback={<Error />}>
          <Navbar />
          <div className="w-full h-full pt-12">
            <AuthProvider>{children}</AuthProvider>
          </div>
          <Toaster />
        </ErrorBoundary>
      </body>
    </html>
  );
}
