import { GeistSans } from "geist/font";
import "./globals.css";
import Navbar from "@/app/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full h-full">
      <body className={GeistSans.className + " w-full h-full flex-col"}>
        <Navbar />
        <div className="w-full h-full pt-12">{children}</div>
      </body>
    </html>
  );
}
